import type { NextPage } from 'next'

import NextLink from 'next/link'

import { useTitle } from 'states/page'

import { Page, PageContent } from 'components/Layout'

import { DataCard } from './DataCard'

const About: NextPage = () => {
	useTitle('About')
	return (
		<Page>
			<PageContent maxWidth={900}>
				<h1 css={(theme) => ({ fontWeight: theme.font.weight.light, marginBottom: '8px' })}>Privacy Policy</h1>
				<small>Last updated: {new Date('08/27/2022').toLocaleString('en-DK', { year: 'numeric', month: 'long', day: 'numeric' })}</small>
				<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
				<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
				<h2>Interpretation and Definitions</h2>
				<h3>Interpretation</h3>
				<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
				<h3>Definitions</h3>
				<p>For the purposes of this Privacy Policy:</p>
				<div
					css={(theme) => ({
						display: 'grid',
						gridTemplateColumns: '1fr 1fr',
						columnGap: '16px',

						[theme.mediaQueries.maxTablet]: {
							gridTemplateColumns: '1fr',
						},
					})}
				>
					<DataCard
						title='Account'
						description='means a unique account created for You to access our Service or parts of our Service.'
					/>
					<DataCard
						title='Company'
						description='(referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Bruhno.'
					/>
					<DataCard
						title='Service'
						description='refers to the Website.'
					/>
					<DataCard
						title='Country'
						description='refers to: Denmark.'
					/>
					<DataCard
						title='Cookies'
						description='are small files that are placed on Your computer, mobile device or any other device by a website.'
					/>
					<DataCard
						title='Device'
						description='means any device that can access the Service such as a computer, a cellphone or a digital tablet.'
					/>
					<DataCard
						title='You'
						description='means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'
					/>
					<DataCard
						title='Usage Data'
						description='refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'
					/>
					<DataCard
						title='Personal Data'
						description='is any information that relates to an identified or identifiable individual.'
					/>
					<DataCard
						title='Website'
						description={<>refers to Bruhno, accessible from <a href='https://bruhno.com' rel='external nofollow noopener noreferrer' target='_blank'>https://bruhno.com</a> and <a href='https://bruhno.dev' rel='external nofollow noopener noreferrer' target='_blank'>https://bruhno.dev</a></>}
					/>
				</div>
				<DataCard
					title='Service Provider'
					description='means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'
				/>
				<h2>Collecting and Using Your Personal Data</h2>
				<h3>Types of Data Collected</h3>
				<h4>Personal Data</h4>
				<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
				<ul>
					<li>
						<p>Email address</p>
					</li>
					<li>
						<p>Usage Data</p>
					</li>
				</ul>
				<h4>Usage Data</h4>
				<p>Usage Data is collected automatically when using the Service.</p>
				<p>Usage Data may include information such as Your Device&apos;s, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit and other diagnostic data.</p>
				<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, Your mobile operating system, the type of mobile Internet browser You use and other diagnostic data.</p>
				<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
				<h3>Cookies</h3>
				<p>We use Cookies to store certain information. The technologies We use may include:</p>
				<DataCard
					title='Cookies or Browser Cookies.'
					description='A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.'
				/>
				<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
				<p>We use Persistent Cookies for the purposes set out below:</p>
				<DataCard
					title='Functionality Cookies'
					caption={(
						<>
							<div>Type: Persistent Cookies</div>
							<div>Administered by: Us</div>
						</>
					)}
					description='Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.'
				/>
				<p>For more information about the cookies we use and your choices regarding cookies, please visit our <NextLink href='/cookies'>Cookies Policy</NextLink> or the Cookies section of our Privacy Policy.</p>
				<h3>Use of Your Personal Data</h3>
				<p>The Company may use Personal Data for the following purposes:</p>
				<ul>
					<li>
						<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
					</li>
					<li>
						<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
					</li>
					<li>
						<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
					</li>
				</ul>
				<p>Your personal information will not be shared to any third-parties.</p>
				<h4>Retention of Your Personal Data</h4>
				<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
				<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
				<h4>Transfer of Your Personal Data</h4>
				<p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
				<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
				<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
				<h3>Disclosure of Your Personal Data</h3>
				<h4>Law enforcement</h4>
				<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
				<h4>Other legal requirements</h4>
				<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
				<ul>
					<li>Comply with a legal obligation</li>
					<li>Protect and defend the rights or property of the Company</li>
					<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
					<li>Protect the personal safety of Users of the Service or the public</li>
					<li>Protect against legal liability</li>
				</ul>
				<h3>Security of Your Personal Data</h3>
				<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
				<h2>Children&apos;s Privacy</h2>
				<p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
				<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.</p>
				<h2>Links to Other Websites</h2>
				<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
				<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
				<h2>Changes to this Privacy Policy</h2>
				<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
				<p>We will let You know via a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
				<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
			</PageContent>
		</Page>
	)
}

export default About
