image: node:latest

cache:
  paths:
  - node_modules/

stages: 
    - build

build:
    stage: build
    script: 
        - echo "Running build"
        - npm install
        - npm cross-env NODE_ENV=production npm run build
