image: node:latest

cache:
  paths:
  - node_modules/
  
lint:
    stage: lint
    script:
        - echo "Running linter"
        - npm install
        - npm run clean
        - npm run lint

build:
    stage: build
    script: 
        - echo "Running build"
        - npm run build:prod

