rules:
  indentation:
    - 2
    - size: tab

  property-sort-order:
    - 0

  no-color-literals:
    - 0

  hex-notation:
    - 2
    - style: uppercase

  force-attribute-nesting:
    - 0

  no-qualifying-elements:
    - 0

  class-name-format:
    - 2
    - convention: camelcase

  leading-zero:
    - 0

  pseudo-element:
    - 0

  force-pseudo-nesting:
    - 0

  force-element-nesting:
    - 0
