name: Test and lint

on: [pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: latest

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm i

    - name: Linting
      run: pnpm lint

    - name: Testing
      run: pnpm test
      env:
        AUTH_IV: ${{ secrets.AUTH_IV }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        VERCEL_ENV: ${{ secrets.VERCEL_ENV }}
        FAUNADB_SECRET: ${{ secrets.FAUNADB_SECRET }}
        FAUNADB_SERVER_KEY: ${{ secrets.FAUNADB_SERVER_KEY }}
        IGDB_USER_KEY: ${{ secrets.IGDB_USER_KEY }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        TESTING_CREDENTIALS: ${{ secrets.TESTING_CREDENTIALS }}
        TESTING_TOKEN: ${{ secrets.TESTING_TOKEN }}
